name: Playwright Tests Cloud Execution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-execution:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --project=api

    - name: Upload Test Report Artifact
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-html-report
        path: playwright-report/
        retention-days: 30


    - name: Send status notification to Slack
      uses: ravsamhq/notify-slack-action@v2
      if: ${{ always() }} # Queremos que nos avise tanto si da verde como si falla
      with:
        status: ${{ job.status }}
        notification_title: 'Resultado de la suite de pruebas en la nube 🤖'
        message_format: '{emoji} *Los tests de API terminaron con estado:* {status_message}'
        footer: 'Pipeline ejecutado por GitHub Actions'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
